# Generated by Django 4.0.1 on 2022-05-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_capacity',
            new_name='sessions_per_day',
        ),
    ]
