# Generated by Django 4.0.1 on 2023-01-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_telegramtouser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramtouser',
            old_name='user_id',
            new_name='user',
        ),
    ]
