# Generated by Django 4.0.1 on 2022-05-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_room_capacity_room_sessions_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='sessions_per_day',
            new_name='session_duration',
        ),
    ]
