# Generated by Django 4.0.1 on 2022-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_sessions_per_day_room_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='Available', max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'start_time', 'booking_room')},
        ),
    ]
