# Generated by Django 4.0.1 on 2023-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_id_telegramtouser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
