# Generated by Django 4.0.1 on 2022-06-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_end_datetime_booking_datetime_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scenario',
            field=models.IntegerField(default=0),
        ),
    ]
