# Generated by Django 4.0.1 on 2022-06-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='scenarios',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Blocking',
        ),
    ]
