# Generated by Django 4.0.1 on 2022-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_room_scenarios_delete_blocking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='datetime_start',
            field=models.DateTimeField(unique=True),
        ),
    ]
