# Generated by Django 4.0.1 on 2022-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pax',
            field=models.IntegerField(default=1),
        ),
    ]
