# Generated by Django 4.0.1 on 2022-06-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_booking_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime_start',
            field=models.DateTimeField(),
        ),
    ]
