# Generated by Django 4.0.1 on 2022-06-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_booking_datetime_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='prep_days',
            field=models.IntegerField(default=0),
        ),
    ]
